version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-reactive-processor
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  couchbase:
    image: couchbase/server
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"