curl https://glp-api.pearson.com/aum/health
curl https://glp-api.pearson.com/autobahnpro/health
curl https://glp-api.pearson.com/cic/health
curl https://glp-api.pearson.com/cma/health
curl https://glp-api.pearson.com/cms/health
curl https://glp-api.pearson.com/cns/health
curl https://glp-api.pearson.com/gbg/health
curl https://glp-api.pearson.com/iam/health
curl https://glp-api.pearson.com/imc/health
curl https://glp-api.pearson.com/lad/health
curl https://glp-api.pearson.com/lap/health
curl https://glp-api.pearson.com/lapp/health
curl https://glp-api.pearson.com/lec/health
curl https://glp-api.pearson.com/lee/health
curl https://glp-api.pearson.com/lms/health
curl https://glp-api.pearson.com/lpb/health
curl https://glp-api.pearson.com/pdz/health
curl https://glp-api.pearson.com/pgp/health
curl https://glp-api.pearson.com/pla/health
curl https://glp-api.pearson.com/rbassignment/health
curl https://glp-api.pearson.com/rbaum/health
curl https://glp-api.pearson.com/rbgradebook/health
curl https://glp-api.pearson.com/rblms/health
curl https://glp-api.pearson.com/registrar/health
curl https://glp-api.pearson.com/roster/health
curl https://glp-api.pearson.com/gms/health
curl https://glp-api.pearson.com/rbassessment/health
curl https://glp-api.pearson.com/assessment/health
curl https://glp-api.pearson.com/lae/health
curl https://glp-api.pearson.com/eviews/health
curl https://glp-api.pearson.com/lcd/health
curl https://glp-api.pearson.com/rblearner/health
curl https://glp-api.pearson.com/cprs/health
curl https://glp-api.pearson.com/scheduler/health
